[tool.black]
line-length = 100
skip-string-normalization = true
exclude = '''
(
  /(
      \.git
    | \.venv
  )/
)
'''

[tool.isort]
# To match black's line length
line_length = 100
include_trailing_comma = true
multi_line_output = 3
known_third_party=["aiohttp", "bs4", "pandas", "pytest", "requests", "urllib3", "yaml"]
